### ISSUE TITLE
prettify GUI?

### ISSUE THREAD

**Issue by davidedelvento** [davidedelvento/runnerup#10]

**Comment by gerhardol** [comment]
Related to #7

**Comment by davidedelvento** [comment]
@gerhardol well, #7 is more about functionality, like #22 whereas this is purely aesthetic. Anyway, I'll be waiting for @cmmata to make his first stab, before doing anything with these.

**Comment by davidedelvento** [comment]
Closing this issue sinc @cmmata will be working on it. Might work on some specifics later.

**Comment by davidedelvento** [comment]
see https://github.com/cmmata/runnerup/issues/1
